/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turism.gui;


import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.*;
import javax.swing.*;
import turism.controle.CidadeDAO;
import turism.controle.EmpresaDAO;
import turism.controle.EstadoDAO;
import turism.controle.HoteisContratadosDAO;
import turism.controle.HotelDAO;
import turism.controle.PaisDAO;
import turism.controle.VeiculoDAO;
import turism.controle.VeiculosContratadosDAO;
import turism.controle.ViagemDAO;
import turism.modelo.Cidade;
import turism.modelo.Empresa;
import turism.modelo.Estado;
import turism.modelo.Hoteiscontratados;
import turism.modelo.Hotel;
import turism.modelo.Pais;
import turism.modelo.Veiculo;
import turism.modelo.Veiculoscontratados;
import turism.modelo.Viagem;
import turism.regra.HoteisContratadosTableModel;
import turism.regra.VeiculosContratadosTableModel;

/**
 *
 * @author matheus
 */
public class TelaViagemVisualizacao extends javax.swing.JFrame {

    //Listas
    ArrayList<Pais> paises = new ArrayList<>();
    ArrayList<Empresa> empresas = new ArrayList<>();
    ArrayList<Hotel> hoteis = new ArrayList<>();
    ArrayList<Hoteiscontratados> hoteiscontratados = new ArrayList<>();
    ArrayList<Veiculoscontratados> veiculoscontratados = new ArrayList<>();

    //Entidades e DAO
    Viagem viagem = new Viagem();
    ViagemDAO vDAO = new ViagemDAO();

    //Modelo Tabela
    VeiculosContratadosTableModel modeloV;
    HoteisContratadosTableModel modeloH;

    //formato dinheiro
    private static final Locale BRAZIL = new Locale("pt", "BR");
    private static final DecimalFormatSymbols REAL = new DecimalFormatSymbols(BRAZIL);
    public static final DecimalFormat DINHEIRO_REAL = new DecimalFormat("¤ ###,###,##0.00", REAL);
    public static final DecimalFormat ITENS = new DecimalFormat("###,###,##0");

    /**
     * Creates new form Viagem
     */
    public TelaViagemVisualizacao() {
        initComponents();
        carregaEmpresa();
        carregaHotel();
        modeloV = new VeiculosContratadosTableModel();
        modeloH = new HoteisContratadosTableModel();
        jtVeiculos.setModel(modeloV);
        jtHotel.setModel(modeloH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOrigem = new javax.swing.JTextField();
        btnBuscaOrigem = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        btnBuscaDestino = new javax.swing.JButton();
        jInternalBuscaCidade = new javax.swing.JInternalFrame();
        jLabel13L = new javax.swing.JLabel();
        jLabel14L = new javax.swing.JLabel();
        jLabel15L = new javax.swing.JLabel();
        jbPais = new javax.swing.JComboBox<>();
        jbEstado = new javax.swing.JComboBox<>();
        jbCidade = new javax.swing.JComboBox<>();
        btnSelecionar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        PainelOnibus = new javax.swing.JPanel();
        jbEmpresa = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbVeiculo = new javax.swing.JComboBox<>();
        btnAdVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVeiculos = new javax.swing.JTable();
        btnRmVeiculo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtValorOnCon = new javax.swing.JSpinner();
        PainelHotel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jbHotel = new javax.swing.JComboBox<>();
        btnAdHotel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHotel = new javax.swing.JTable();
        btnRmHotel = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtValorHtCon = new javax.swing.JSpinner();
        jTPViagem = new javax.swing.JTabbedPane();
        PainelVisualizacao = new javax.swing.JPanel();
        PainelOrigem = new javax.swing.JPanel();
        txtOrigemVisu = new javax.swing.JTextField();
        PainelDestino = new javax.swing.JPanel();
        txtDestinoVisu = new javax.swing.JTextField();
        PainelAll = new javax.swing.JPanel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR);
        txtHoraSaida = new javax.swing.JSpinner(sm);
        jLabel5 = new javax.swing.JLabel();
        dataVolta = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dataIda = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVagaRestante = new javax.swing.JTextField();
        txtVagaTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValorPessoa = new javax.swing.JTextField();
        txtValorOnibus = new javax.swing.JTextField();
        txtValorHotel = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        painelFuncoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();

        txtOrigem.setEditable(false);
        txtOrigem.setEnabled(false);

        btnBuscaOrigem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaOrigemActionPerformed(evt);
            }
        });

        txtDestino.setEditable(false);
        txtDestino.setEnabled(false);

        btnBuscaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaDestinoActionPerformed(evt);
            }
        });

        jInternalBuscaCidade.setTitle("Busca Cidade");
        jInternalBuscaCidade.setVisible(false);
        jInternalBuscaCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInternalBuscaCidadeFocusGained(evt);
            }
        });
        jInternalBuscaCidade.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalBuscaCidadeInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel13L.setText("País:");

        jLabel14L.setText("Estado:");

        jLabel15L.setText("Cidade:");

        jbPais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbPaisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbPaisFocusLost(evt);
            }
        });

        jbEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbEstadoFocusLost(evt);
            }
        });
        jbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstadoActionPerformed(evt);
            }
        });

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalBuscaCidadeLayout = new javax.swing.GroupLayout(jInternalBuscaCidade.getContentPane());
        jInternalBuscaCidade.getContentPane().setLayout(jInternalBuscaCidadeLayout);
        jInternalBuscaCidadeLayout.setHorizontalGroup(
            jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBuscaCidadeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13L)
                    .addComponent(jbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelecionar)
                    .addGroup(jInternalBuscaCidadeLayout.createSequentialGroup()
                        .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14L))
                        .addGap(67, 67, 67)
                        .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15L)
                            .addComponent(jbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalBuscaCidadeLayout.setVerticalGroup(
            jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBuscaCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13L)
                    .addComponent(jLabel14L)
                    .addComponent(jLabel15L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalBuscaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSelecionar)
                .addGap(26, 26, 26))
        );

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/add_64.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        PainelOnibus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ônibus"));

        jbEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbEmpresaItemStateChanged(evt);
            }
        });

        jLabel17.setText("Empresa:");

        jLabel18.setText("Veículo:");

        btnAdVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/add_16.png"))); // NOI18N
        btnAdVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdVeiculoActionPerformed(evt);
            }
        });

        jtVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtVeiculos);

        btnRmVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/close_16.png"))); // NOI18N
        btnRmVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmVeiculoActionPerformed(evt);
            }
        });

        jLabel20.setText("Valor:");

        txtValorOnCon.setModel(new javax.swing.SpinnerNumberModel(100.0d, null, null, 1.0d));

        javax.swing.GroupLayout PainelOnibusLayout = new javax.swing.GroupLayout(PainelOnibus);
        PainelOnibus.setLayout(PainelOnibusLayout);
        PainelOnibusLayout.setHorizontalGroup(
            PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOnibusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelOnibusLayout.createSequentialGroup()
                        .addComponent(btnAdVeiculo)
                        .addGap(31, 31, 31)
                        .addComponent(btnRmVeiculo))
                    .addComponent(jLabel18)
                    .addComponent(jbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtValorOnCon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(PainelOnibusLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelOnibusLayout.setVerticalGroup(
            PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOnibusLayout.createSequentialGroup()
                .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelOnibusLayout.createSequentialGroup()
                        .addGroup(PainelOnibusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorOnCon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRmVeiculo))
                    .addComponent(btnAdVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        PainelHotel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hotel"));

        jLabel19.setText("Hotel:");

        btnAdHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/add_16.png"))); // NOI18N
        btnAdHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdHotelActionPerformed(evt);
            }
        });

        jtHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtHotel);

        btnRmHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/close_16.png"))); // NOI18N
        btnRmHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmHotelActionPerformed(evt);
            }
        });

        jLabel21.setText("Valor:");

        txtValorHtCon.setModel(new javax.swing.SpinnerNumberModel(250.0d, null, null, 1.0d));

        javax.swing.GroupLayout PainelHotelLayout = new javax.swing.GroupLayout(PainelHotel);
        PainelHotel.setLayout(PainelHotelLayout);
        PainelHotelLayout.setHorizontalGroup(
            PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHotelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHotelLayout.createSequentialGroup()
                        .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelHotelLayout.createSequentialGroup()
                                .addComponent(btnAdHotel)
                                .addGap(61, 61, 61)
                                .addComponent(btnRmHotel))
                            .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txtValorHtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PainelHotelLayout.setVerticalGroup(
            PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHotelLayout.createSequentialGroup()
                .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbHotel)
                    .addComponent(txtValorHtCon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelHotelLayout.createSequentialGroup()
                        .addComponent(btnAdHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .addGroup(PainelHotelLayout.createSequentialGroup()
                        .addComponent(btnRmHotel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viagem");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelOrigem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Origem:"));

        txtOrigemVisu.setEditable(false);

        javax.swing.GroupLayout PainelOrigemLayout = new javax.swing.GroupLayout(PainelOrigem);
        PainelOrigem.setLayout(PainelOrigemLayout);
        PainelOrigemLayout.setHorizontalGroup(
            PainelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrigemLayout.createSequentialGroup()
                .addComponent(txtOrigemVisu, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        PainelOrigemLayout.setVerticalGroup(
            PainelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOrigemVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PainelDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Destino:"));

        txtDestinoVisu.setEditable(false);

        javax.swing.GroupLayout PainelDestinoLayout = new javax.swing.GroupLayout(PainelDestino);
        PainelDestino.setLayout(PainelDestinoLayout);
        PainelDestinoLayout.setHorizontalGroup(
            PainelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDestinoLayout.createSequentialGroup()
                .addComponent(txtDestinoVisu, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        PainelDestinoLayout.setVerticalGroup(
            PainelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDestinoVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PainelAll.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JSpinner.DateEditor de = new JSpinner.DateEditor(txtHoraSaida, "HH:mm");
        txtHoraSaida.setEditor(de);
        txtHoraSaida.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        txtHoraSaida.setEnabled(false);

        jLabel5.setText("Horário Saída:");

        dataVolta.setEnabled(false);

        jLabel4.setText("Data de Volta:");

        dataIda.setEnabled(false);
        dataIda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataIdaPropertyChange(evt);
            }
        });

        jLabel3.setText("Data de Ida:");

        jLabel6.setText("Vagas Total:");

        jLabel7.setText("Vagas Restante:");

        txtVagaRestante.setEditable(false);
        txtVagaRestante.setEnabled(false);

        txtVagaTotal.setEditable(false);
        txtVagaTotal.setEnabled(false);

        jLabel8.setText("Vagas Extras:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());
        jSpinner1.setEnabled(false);

        jLabel9.setText("Valor por Pessoa:");

        jLabel10.setText("Valor do Ônibus:");

        jLabel11.setText("Valor do Hotel:");

        txtValorPessoa.setEditable(false);
        txtValorPessoa.setEnabled(false);

        txtValorOnibus.setEditable(false);
        txtValorOnibus.setEnabled(false);
        txtValorOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorOnibusActionPerformed(evt);
            }
        });

        txtValorHotel.setEditable(false);
        txtValorHotel.setEnabled(false);

        txtValorTotal.setEditable(false);
        txtValorTotal.setEnabled(false);

        jLabel12.setText("Valor Total:");

        jLabel22.setText("Descrição:");

        txtDescricao.setEnabled(false);
        jScrollPane3.setViewportView(txtDescricao);

        jLabel1.setText("Valor Recebido:");

        jLabel2.setText("Valor Faltante:");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        javax.swing.GroupLayout PainelAllLayout = new javax.swing.GroupLayout(PainelAll);
        PainelAll.setLayout(PainelAllLayout);
        PainelAllLayout.setHorizontalGroup(
            PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAllLayout.createSequentialGroup()
                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAllLayout.createSequentialGroup()
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAllLayout.createSequentialGroup()
                                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtVagaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelAllLayout.createSequentialGroup()
                                        .addComponent(txtVagaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelAllLayout.createSequentialGroup()
                                        .addComponent(txtValorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValorHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1)))
                                    .addGroup(PainelAllLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))))
                            .addGroup(PainelAllLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(PainelAllLayout.createSequentialGroup()
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dataIda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PainelAllLayout.setVerticalGroup(
            PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAllLayout.createSequentialGroup()
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dataIda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVagaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVagaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(PainelAllLayout.createSequentialGroup()
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAllLayout.createSequentialGroup()
                                .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addGroup(PainelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtValorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtValorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtValorHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelAllLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataIda.getJCalendar().setMinSelectableDate(new Date());

        painelFuncoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/save_64.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFuncoesLayout = new javax.swing.GroupLayout(painelFuncoes);
        painelFuncoes.setLayout(painelFuncoesLayout);
        painelFuncoesLayout.setHorizontalGroup(
            painelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        painelFuncoesLayout.setVerticalGroup(
            painelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFuncoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        javax.swing.GroupLayout PainelVisualizacaoLayout = new javax.swing.GroupLayout(PainelVisualizacao);
        PainelVisualizacao.setLayout(PainelVisualizacaoLayout);
        PainelVisualizacaoLayout.setHorizontalGroup(
            PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                        .addComponent(PainelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelFuncoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                        .addComponent(PainelOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PainelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelVisualizacaoLayout.setVerticalGroup(
            PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                .addGroup(PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(painelFuncoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 386, Short.MAX_VALUE))
        );

        jTPViagem.addTab("Visualização", PainelVisualizacao);

        getContentPane().add(jTPViagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataIdaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataIdaPropertyChange
        // TODO add your handling code here:
        dataVolta.getJCalendar().setMinSelectableDate(dataIda.getDate());
        dataVolta.setDate(dataIda.getDate());
    }//GEN-LAST:event_dataIdaPropertyChange

    private void jInternalBuscaCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalBuscaCidadeFocusGained
        // TODO add your handling code here:
        PaisDAO pDAO = new PaisDAO();
        paises = pDAO.buscaPaises("");
        jbPais.removeAllItems();
        paises.forEach((next) -> {
            jbPais.addItem(next.getNome());
        });
        jbPais.setSelectedIndex(-1);
        jbEstado.removeAllItems();
        jbEstado.setSelectedIndex(-1);
        jbCidade.removeAllItems();
        jbCidade.setSelectedIndex(-1);
    }//GEN-LAST:event_jInternalBuscaCidadeFocusGained

    private void btnBuscaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaOrigemActionPerformed
        // TODO add your handling code here:
        chaveBackground(false);
        jInternalBuscaCidade.setVisible(true);
        jInternalBuscaCidade.toFront();
        jInternalBuscaCidade.setClosable(true);
        jInternalBuscaCidade.requestFocus();
    }//GEN-LAST:event_btnBuscaOrigemActionPerformed

    private void jInternalBuscaCidadeInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalBuscaCidadeInternalFrameClosed
        // TODO add your handling code here:
        chaveBackground(true);
    }//GEN-LAST:event_jInternalBuscaCidadeInternalFrameClosed

    private void jbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEstadoActionPerformed

    private void jbPaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbPaisFocusLost
        // TODO add your handling code here:
        int indice = jbPais.getSelectedIndex();
        if (indice >= 0) {
            PaisDAO pDAO = new PaisDAO();
            Pais p = pDAO.buscaPais(indice + 1);
            jbEstado.removeAllItems();
            if (!p.getEstadoList().isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstado.addItem(next.getUf());
                });
                jbEstado.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisFocusLost

    private void jbEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbEstadoFocusLost
        // TODO add your handling code here:
        int indice = jbEstado.getSelectedIndex();
        if (indice >= 0) {
            EstadoDAO eDAO = new EstadoDAO();
            Estado e = eDAO.buscaEstado(indice + 1);
            jbCidade.removeAllItems();
            if (!e.getCidadeList().isEmpty()) {
                e.getCidadeList().forEach((next) -> {
                    jbCidade.addItem(next.getNome());
                });
                jbCidade.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbEstadoFocusLost

    private void jbPaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbPaisFocusGained
        // TODO add your handling code here:
        jbEstado.removeAllItems();
        jbEstado.setSelectedIndex(-1);
        jbCidade.removeAllItems();
        jbCidade.setSelectedIndex(-1);
        jbCidade.removeAllItems();
        jbCidade.setSelectedIndex(-1);
    }//GEN-LAST:event_jbPaisFocusGained

    private void jbEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbEstadoFocusGained
        // TODO add your handling code here:
        jbCidade.removeAllItems();
        jbCidade.setSelectedIndex(-1);
    }//GEN-LAST:event_jbEstadoFocusGained

    private void btnBuscaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaDestinoActionPerformed
        // TODO add your handling code here:
        chaveBackground(false);
        jInternalBuscaCidade.setVisible(true);
        jInternalBuscaCidade.toFront();
        jInternalBuscaCidade.setClosable(true);
        jInternalBuscaCidade.requestFocus();
    }//GEN-LAST:event_btnBuscaDestinoActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        /* int indice = jbCidade.getSelectedIndex();
        CidadeDAO cDAO = new CidadeDAO();
        Cidade cidade = cDAO.buscaCidade(indice + 1);
        if (chave) {
            txtOrigem.setText(cidade.getNome());
            viagem.setIdorigem(cidade);
            jbCidade.removeAllItems();
            jbEstado.removeAllItems();
            jbPais.removeAllItems();
            try {
                jInternalBuscaCidade.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaViagemCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            txtDestino.setText(cidade.getNome());
            viagem.setIddestino(cidade);
            jbCidade.removeAllItems();
            jbEstado.removeAllItems();
            jbPais.removeAllItems();
            try {
                System.err.println("Entrou");
                jInternalBuscaCidade.setClosed(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, "Erro: "+ex);
                Logger.getLogger(TelaViagemCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtValorOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorOnibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorOnibusActionPerformed

    private void jbEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbEmpresaItemStateChanged
        // TODO add your handling code here:
        carregaVeiculo(jbEmpresa.getSelectedIndex());
    }//GEN-LAST:event_jbEmpresaItemStateChanged

    private void btnAdVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdVeiculoActionPerformed
        // TODO add your handling code here:
        int indice = jbVeiculo.getSelectedIndex();
        if (indice >= 0) {
            VeiculoDAO veDAO = new VeiculoDAO();
            Veiculo v = veDAO.buscaVeiculo(indice + 1);
            Veiculoscontratados vc = new Veiculoscontratados();
            vc.setVeiculo(v);
            vc.setViagem(viagem);
            vc.setValor(Double.valueOf(txtValorOnCon.getValue().toString()));
            if (veiculoscontratados.contains(vc)) {
                JOptionPane.showMessageDialog(this, "Veículo já adicionado");
            } else {
                veiculoscontratados.add(vc);
                modeloV.addItem(vc);
                this.vagasTotal();
                this.valorTotal();
            }
        }
    }//GEN-LAST:event_btnAdVeiculoActionPerformed

    private void btnRmVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmVeiculoActionPerformed
        // TODO add your handling code here:
        veiculoscontratados.remove(jtVeiculos.getSelectedRow());
        modeloV.limpar();
        modeloV.addListaVeiculosContratados(veiculoscontratados);
        this.vagasTotal();
        this.valorTotal();
    }//GEN-LAST:event_btnRmVeiculoActionPerformed

    private void btnAdHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdHotelActionPerformed
        // TODO add your handling code here:
        int indice = jbHotel.getSelectedIndex();
        if (indice >= 0) {
            HotelDAO hDAO = new HotelDAO();
            Hotel h = hDAO.buscaHotel(indice + 1);
            Hoteiscontratados hc = new Hoteiscontratados();
            hc.setHotel(h);
            hc.setViagem(viagem);
            hc.setValor(Double.valueOf(txtValorHtCon.getValue().toString()));
            if (hoteiscontratados.contains(hc)) {
                JOptionPane.showMessageDialog(this, "Hotel já adicionado");
            } else {
                hoteiscontratados.add(hc);
                modeloH.addItem(hc);
                this.valorTotal();
            }
        }
    }//GEN-LAST:event_btnAdHotelActionPerformed

    private void btnRmHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmHotelActionPerformed
        // TODO add your handling code here:
        hoteiscontratados.remove(jtHotel.getSelectedRow());
        modeloH.limpar();
        modeloH.addListaHoteisContratados(hoteiscontratados);
        this.valorTotal();
    }//GEN-LAST:event_btnRmHotelActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (this.carregaViagem()) {
            if (viagem.getIdviagem() == null) {
                vDAO.adicionar(viagem);
                VeiculosContratadosDAO vcDAO = new VeiculosContratadosDAO();
                HoteisContratadosDAO hcDAO = new HoteisContratadosDAO();
                veiculoscontratados.forEach((next) -> {
                    vcDAO.adicionar(next);
                });

                hoteiscontratados.forEach((hc) -> {
                    hcDAO.adicionar(hc);
                });
                JOptionPane.showMessageDialog(this, "Viagem cadastrada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Viagem já cadastrada!.");
            }

        } else {

        }
        viagem = new Viagem();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaViagemVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaViagemVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaViagemVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaViagemVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaViagemVisualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAll;
    private javax.swing.JPanel PainelDestino;
    private javax.swing.JPanel PainelHotel;
    private javax.swing.JPanel PainelOnibus;
    private javax.swing.JPanel PainelOrigem;
    private javax.swing.JPanel PainelVisualizacao;
    private javax.swing.JButton btnAdHotel;
    private javax.swing.JButton btnAdVeiculo;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscaDestino;
    private javax.swing.JButton btnBuscaOrigem;
    private javax.swing.JButton btnRmHotel;
    private javax.swing.JButton btnRmVeiculo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionar;
    private com.toedter.calendar.JDateChooser dataIda;
    private com.toedter.calendar.JDateChooser dataVolta;
    private javax.swing.JInternalFrame jInternalBuscaCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13L;
    private javax.swing.JLabel jLabel14L;
    private javax.swing.JLabel jLabel15L;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTPViagem;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jbCidade;
    private javax.swing.JComboBox<String> jbEmpresa;
    private javax.swing.JComboBox<String> jbEstado;
    private javax.swing.JComboBox<String> jbHotel;
    private javax.swing.JComboBox<String> jbPais;
    private javax.swing.JComboBox<String> jbVeiculo;
    private javax.swing.JTable jtHotel;
    private javax.swing.JTable jtVeiculos;
    private javax.swing.JPanel painelFuncoes;
    private javax.swing.JTextPane txtDescricao;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDestinoVisu;
    private javax.swing.JSpinner txtHoraSaida;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtOrigemVisu;
    private javax.swing.JTextField txtVagaRestante;
    private javax.swing.JTextField txtVagaTotal;
    private javax.swing.JTextField txtValorHotel;
    private javax.swing.JSpinner txtValorHtCon;
    private javax.swing.JSpinner txtValorOnCon;
    private javax.swing.JTextField txtValorOnibus;
    private javax.swing.JTextField txtValorPessoa;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

    private void chaveBackground(boolean v) {
        btnBuscaDestino.setVisible(v);
        btnBuscaOrigem.setVisible(v);
        dataIda.setVisible(v);
        dataVolta.setVisible(v);
        jLabel10.setVisible(v);
        jLabel11.setVisible(v);
        jLabel12.setVisible(v);
        jLabel3.setVisible(v);
        jLabel4.setVisible(v);
        jLabel5.setVisible(v);
        jLabel6.setVisible(v);
        jLabel7.setVisible(v);
        jLabel8.setVisible(v);
        jLabel9.setVisible(v);
        jSpinner1.setVisible(v);
        txtDestino.setVisible(v);
        txtHoraSaida.setVisible(v);
        txtOrigem.setVisible(v);
        txtVagaTotal.setVisible(v);
        txtVagaRestante.setVisible(v);
        txtValorHotel.setVisible(v);
        txtValorOnibus.setVisible(v);
        txtValorPessoa.setVisible(v);
        txtValorTotal.setVisible(v);
    }

    private void carregaEmpresa() {
        EmpresaDAO eDAO = new EmpresaDAO();
        empresas = eDAO.buscaEmpresas("");
        jbEmpresa.removeAllItems();
        empresas.forEach((next) -> {
            jbEmpresa.addItem(next.getNome());
        });
        jbEmpresa.setSelectedIndex(-1);
    }

    private void carregaVeiculo(int indice) {
        jbVeiculo.removeAllItems();
        if (indice >= 0) {
            EmpresaDAO eDAO = new EmpresaDAO();
            Empresa empresa = eDAO.buscaEmpresa(indice + 1);
            empresa.getVeiculoList().forEach((next) -> {
                jbVeiculo.addItem(next.getNome());
            });
            jbVeiculo.setSelectedIndex(-1);
        }
    }

    private void carregaHotel() {
        HotelDAO hDAO = new HotelDAO();
        hoteis = hDAO.buscaHoteis("");
        jbHotel.removeAllItems();
        hoteis.forEach((next) -> {
            jbHotel.addItem(next.getNome());
        });
        jbHotel.setSelectedIndex(-1);
    }

    private int vagasTotal() {
        int total = 0;
        if (!veiculoscontratados.isEmpty()) {
            total = veiculoscontratados.stream().map((next) -> next.getVeiculo().getLotacao()).reduce(total, Integer::sum);
        }
        txtVagaTotal.setText(String.valueOf(ITENS.format(total)));
        return total;
    }

    private void valorTotal() {
        double total = 0, onibus = 0, hotel = 0;
        if (!veiculoscontratados.isEmpty()) {
            for (Veiculoscontratados next : veiculoscontratados) {
                if (next.getValor() > onibus) {
                    onibus = next.getValor();
                }
            }
            txtValorOnibus.setText(String.valueOf(DINHEIRO_REAL.format(onibus * this.vagasTotal())));
        }
        if (!hoteiscontratados.isEmpty()) {
            for (Hoteiscontratados hoteu : hoteiscontratados) {
                if (hoteu.getValor() > hotel) {
                    hotel = hoteu.getValor();
                }
            }
            txtValorHotel.setText(String.valueOf(DINHEIRO_REAL.format(hotel * this.vagasTotal())));
        }
        if (veiculoscontratados.isEmpty()) {
            txtValorOnibus.setText(String.valueOf(DINHEIRO_REAL.format(onibus * this.vagasTotal())));
        }
        if (hoteiscontratados.isEmpty()) {
            txtValorHotel.setText(String.valueOf(DINHEIRO_REAL.format(hotel * this.vagasTotal())));
        }
        total = onibus + hotel;

        txtValorPessoa.setText(String.valueOf(DINHEIRO_REAL.format(total)));
        txtValorTotal.setText(String.valueOf(DINHEIRO_REAL.format(total * this.vagasTotal())));
    }
    
    private boolean carregaViagem() {
        boolean c = false, d = false;
        if (viagem.getIdorigem() != null && viagem.getIddestino() != null) {
            c = true;
        }else{
            JOptionPane.showMessageDialog(this, "Escolha cidade de Origem e Destino!");
        }
        if (this.dataIda.getDate() != null && this.dataVolta.getDate() != null
                && this.txtHoraSaida.getValue().toString() != null) {
            viagem.setDataida(dataIda.getDate());
            viagem.setDatavolta(dataVolta.getDate());
            Date data = (Date) txtHoraSaida.getValue();
            System.err.println(data);
            viagem.setHorariosaida(data);
            d = true;
        }else{
            JOptionPane.showMessageDialog(this, "Escolha data de ida e volta e horário de saída!");
        }
        viagem.setVagasextras(Integer.valueOf(jSpinner1.getValue().toString()));
        viagem.setDescricao(txtDescricao.getText());
        return c && d;
    }
}
