/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turism.gui;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import turism.controle.AssentoDAO;
import turism.controle.ClienteDAO;
import turism.controle.ContratoDAO;
import turism.controle.DepedenteDAO;
import turism.controle.HotelDAO;
import turism.controle.OcupanteDAO;
import turism.controle.QuartoDAO;
import turism.modelo.Assento;
import turism.modelo.AssentoPK;
import turism.modelo.Cliente;
import turism.modelo.Contrato;
import turism.modelo.Depedente;
import turism.modelo.Hoteiscontratados;
import turism.modelo.Hotel;
import turism.modelo.Ocupantes;
import turism.modelo.OcupantesPK;
import turism.modelo.Quarto;
import turism.regra.DepedenteTableModel;
import turism.regra.OcupanteTableModel;

/**
 *
 * @author matheus
 */
public class TelaHotelQuarto extends javax.swing.JFrame {
  
    Hoteiscontratados hotelcontratado = new Hoteiscontratados();
    Hotel hotel = new Hotel();
    HotelDAO hDAO = new HotelDAO();
    
    Quarto quarto = new Quarto();
    QuartoDAO qDAO = new QuartoDAO();
    ArrayList<Quarto> quartos = new ArrayList<>();
    
    ArrayList<Ocupantes> ocupantes = new ArrayList<>();

    AssentoDAO aDAO = new AssentoDAO();

    ArrayList<Assento> assentos = new ArrayList<>();
    ArrayList<AssentoPK> assentosPK = new ArrayList<>();

//    ArrayList<Veiculoscontratados> veiculoscontratados = new ArrayList<>();
//    ArrayList<VeiculoscontratadosPK> veiculoscontratadospk = new ArrayList<>();
    
    Cliente cliente = new Cliente();
    Contrato contrato = new Contrato();
    ArrayList<Cliente> clientes = new ArrayList<>();
    ArrayList<Depedente> depedentes = new ArrayList<>();

    DepedenteTableModel modeloDepedente;
    OcupanteTableModel modeloOcupante;

    /**
     * Creates new form TelaVeiculo
     */
    public TelaHotelQuarto() {
        initComponents();
        carregaTable();
    }

    public TelaHotelQuarto(Hoteiscontratados h, String viagem) {
        initComponents();
        hotel = h.getHotel();
        hotelcontratado = h;
        carregaTable();
        carregaTela(viagem);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelOrganizaQuarto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHotel = new javax.swing.JLabel();
        lbViagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelQuarto = new javax.swing.JPanel();
        painelCaQuarto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTXAOBS = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtCamaCasal = new javax.swing.JSpinner();
        txtCamaSolteiro = new javax.swing.JSpinner();
        painelCliente = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBDepedente = new javax.swing.JCheckBox();
        painelDepedente = new javax.swing.JPanel();
        jSPDepedente = new javax.swing.JScrollPane();
        jtDepedente = new javax.swing.JTable();
        btnAdicionarOcupante = new javax.swing.JButton();
        painelOcupantes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTOcupantes = new javax.swing.JTable();
        btnRemoveOcupante = new javax.swing.JButton();
        painelBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jBusca = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBusca = new javax.swing.JList<>();
        txtBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Veículo");

        painelOrganizaQuarto.setMinimumSize(new java.awt.Dimension(806, 627));
        painelOrganizaQuarto.setPreferredSize(new java.awt.Dimension(806, 627));

        jLabel1.setText("Hotel:");

        lbHotel.setText("Hotel");

        lbViagem.setText("ORIGEM Á DESTINO DATA: dd/MM/YYYY");

        jLabel2.setText("Viagem:");

        painelQuarto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelQuarto.setMinimumSize(new java.awt.Dimension(300, 700));

        painelCaQuarto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quarto"));

        jLabel3.setText("Camas de Casal:");

        jLabel4.setText("Camas de Solteiro:");

        jTXAOBS.setColumns(20);
        jTXAOBS.setRows(5);
        jScrollPane1.setViewportView(jTXAOBS);

        jLabel5.setText("Observação:");

        txtCamaCasal.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtCamaSolteiro.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout painelCaQuartoLayout = new javax.swing.GroupLayout(painelCaQuarto);
        painelCaQuarto.setLayout(painelCaQuartoLayout);
        painelCaQuartoLayout.setHorizontalGroup(
            painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCaQuartoLayout.createSequentialGroup()
                .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(painelCaQuartoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCamaCasal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(painelCaQuartoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtCamaSolteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        painelCaQuartoLayout.setVerticalGroup(
            painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCaQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCaQuartoLayout.createSequentialGroup()
                        .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCamaSolteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCaQuartoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCamaCasal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCliente.setEditable(false);

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente:");

        jCBDepedente.setText("Depedentes");
        jCBDepedente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBDepedenteItemStateChanged(evt);
            }
        });

        painelDepedente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtDepedente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPDepedente.setViewportView(jtDepedente);

        javax.swing.GroupLayout painelDepedenteLayout = new javax.swing.GroupLayout(painelDepedente);
        painelDepedente.setLayout(painelDepedenteLayout);
        painelDepedenteLayout.setHorizontalGroup(
            painelDepedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(painelDepedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelDepedenteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSPDepedente, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelDepedenteLayout.setVerticalGroup(
            painelDepedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
            .addGroup(painelDepedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelDepedenteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSPDepedente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnAdicionarOcupante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/add_16.png"))); // NOI18N
        btnAdicionarOcupante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarOcupante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarOcupante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarOcupanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDepedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addComponent(jCBDepedente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnAdicionarOcupante)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAdicionarOcupante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCBDepedente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDepedente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelQuartoLayout = new javax.swing.GroupLayout(painelQuarto);
        painelQuarto.setLayout(painelQuartoLayout);
        painelQuartoLayout.setHorizontalGroup(
            painelQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuartoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCaQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelQuartoLayout.setVerticalGroup(
            painelQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCaQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTOcupantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTOcupantes);

        javax.swing.GroupLayout painelOcupantesLayout = new javax.swing.GroupLayout(painelOcupantes);
        painelOcupantes.setLayout(painelOcupantesLayout);
        painelOcupantesLayout.setHorizontalGroup(
            painelOcupantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOcupantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelOcupantesLayout.setVerticalGroup(
            painelOcupantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOcupantesLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRemoveOcupante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/close_16.png"))); // NOI18N
        btnRemoveOcupante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveOcupante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveOcupante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOcupanteActionPerformed(evt);
            }
        });

        painelBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/add_64.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/save_64.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/delete_64.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(12, 12, 12)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOrganizaQuartoLayout = new javax.swing.GroupLayout(painelOrganizaQuarto);
        painelOrganizaQuarto.setLayout(painelOrganizaQuartoLayout);
        painelOrganizaQuartoLayout.setHorizontalGroup(
            painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(painelQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelOcupantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoveOcupante)
                .addContainerGap())
            .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lbViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
        painelOrganizaQuartoLayout.setVerticalGroup(
            painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnRemoveOcupante))
                            .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(painelOcupantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelOrganizaQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelOrganizaQuartoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(563, Short.MAX_VALUE)))
        );

        jBusca.setClosable(true);
        jBusca.setTitle("Busca Cliente");
        jBusca.setVisible(false);
        jBusca.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jBuscaInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        listBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listBusca);

        txtBusca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaCaretUpdate(evt);
            }
        });
        txtBusca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout jBuscaLayout = new javax.swing.GroupLayout(jBusca.getContentPane());
        jBusca.getContentPane().setLayout(jBuscaLayout);
        jBuscaLayout.setHorizontalGroup(
            jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(txtBusca))
                .addContainerGap())
        );
        jBuscaLayout.setVerticalGroup(
            jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelOrganizaQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelOrganizaQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        this.chaveBackground(false);
        jBusca.setVisible(true);
        txtBusca.requestFocus();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void jCBDepedenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDepedenteItemStateChanged
        // TODO add your handling code here:
        if (jCBDepedente.isSelected() == true) {
            System.err.println(cliente.getIdcliente());
            if (cliente.getIdcliente() != null) {
                painelDepedente.setVisible(true);
                depedentes.clear();
                DepedenteDAO dDAO = new DepedenteDAO();
                depedentes = dDAO.buscaDepedenteCliente(cliente.getIdcliente());
                modeloDepedente.limpar();
                modeloDepedente.addListaDepedente(depedentes);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cliente!");
            }
        } else {
            painelDepedente.setVisible(false);
            depedentes.clear();
        }
    }//GEN-LAST:event_jCBDepedenteItemStateChanged

    private void btnAdicionarOcupanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarOcupanteActionPerformed
        // TODO add your handling code here:
        Ocupantes ocupante = new Ocupantes();
        OcupantesPK opk = new OcupantesPK();

        if (contrato.getIdcontrato() != null && hotel.getIdhotel() != null) {
            opk.setContratoIdcontrato(contrato.getIdcontrato());
            ocupante.setOcupantesPK(opk);
            ocupante.setContrato(contrato);
            ocupante.setQuarto(quarto);
            if (jCBDepedente.isSelected()) {
                int indice = jtDepedente.getSelectedRow();
                if (indice > -1) {
                    ocupante.setNome(depedentes.get(indice).getNome());
                } else {
                    ocupante.setNome(cliente.getNome());
                }
            } else {
                ocupante.setNome(cliente.getNome());
            }
            ocupantes.add(ocupante);
            modeloOcupante.addItem(ocupante);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }
    }//GEN-LAST:event_btnAdicionarOcupanteActionPerformed

    private void btnRemoveOcupanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOcupanteActionPerformed
        // TODO add your handling code here:
        int indice = jTOcupantes.getSelectedRow();
        if (indice > -1) {
            ocupantes.remove(indice);
            modeloOcupante.removeItem(indice);
        }
    }//GEN-LAST:event_btnRemoveOcupanteActionPerformed

    private void listBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBuscaMouseClicked
        // TODO add your handling code here:
        int indice = listBusca.getSelectedIndex();
        if (indice >= 0) {
            cliente = clientes.get(indice);
            ContratoDAO ctDAO = new ContratoDAO();
            ArrayList<Contrato> contratos = ctDAO.buscaContratoViagem(hotelcontratado.getViagem().getIdviagem());
            contratos.stream().filter((c) -> (c.getIdcliente().equals(cliente))).forEachOrdered((c) -> {
                contrato = c;
            });
            DepedenteDAO dDAO = new DepedenteDAO();
            depedentes = dDAO.buscaDepedenteCliente(cliente.getIdcliente());
        }
        jBusca.setVisible(false);
        this.chaveBackground(true);
        txtCliente.setText(cliente.getNome());
        jCBDepedente.setSelected(true);
        jCBDepedenteItemStateChanged(null);
    }//GEN-LAST:event_listBuscaMouseClicked

    private void txtBuscaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaCaretUpdate
        // TODO add your handling code here:
        ClienteDAO ciDAO = new ClienteDAO();
        clientes = ciDAO.buscaClienteViagem(hotelcontratado.getHoteiscontratadosPK().getViagemIdviagem(), txtBusca.getText());
        listBusca.removeAll();
        DefaultListModel modelol = new DefaultListModel();
        clientes.forEach((next) -> {
            modelol.addElement(next.getNome());
        });
        listBusca.setModel(modelol);
        listBusca.repaint();
    }//GEN-LAST:event_txtBuscaCaretUpdate

    private void txtBuscaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaInputMethodTextChanged

    private void jBuscaInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jBuscaInternalFrameClosed
        // TODO add your handling code here:
        this.chaveBackground(true);
        jBusca.setVisible(false);
    }//GEN-LAST:event_jBuscaInternalFrameClosed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtCamaCasal.setValue(0);
        txtCamaSolteiro.setValue(0);
        txtCliente.setText("");
        jTXAOBS.setText("");
        
        modeloOcupante.limpar();
        modeloDepedente.limpar();
        
        quarto = new Quarto();
        cliente = new Cliente();
        ocupantes.clear();
        quartos.clear();
        clientes.clear();
        assentos.clear();
        assentosPK.clear();
        contrato = null;
        depedentes.clear();
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        int cama = Integer.valueOf(txtCamaCasal.getValue().toString());
        quarto.setCamacasal(cama);
        cama = Integer.valueOf(txtCamaSolteiro.getValue().toString());
        quarto.setCamasolteiro(cama);
        quarto.setIdhotel(hotel);
        quarto.setObservacao(jTXAOBS.getText());
        
        if(quarto.getIdquarto() == null){
            qDAO.adiciona(quarto);
        }else{
            qDAO.atualiza(quarto);
        }
        
        OcupanteDAO oDAO = new OcupanteDAO();
        
        if(!oDAO.buscaOcupantes(quarto.getIdquarto()).isEmpty()){
            oDAO.buscaOcupantes(quarto.getIdquarto()).forEach((oc) -> {
                oDAO.apagar(oc);
            });
        }
        
        ocupantes.stream().map((oc) -> {
            oc.setQuarto(quarto);
            return oc;
        }).forEachOrdered((oc) -> {
            oDAO.adicionar(oc);
        });
        
        JOptionPane.showMessageDialog(this, "Quarto e Ocupantes adicinado com Sucesso!s");
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHotelQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaHotelQuarto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarOcupante;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemoveOcupante;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JInternalFrame jBusca;
    private javax.swing.JCheckBox jCBDepedente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jSPDepedente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTOcupantes;
    private javax.swing.JTextArea jTXAOBS;
    private javax.swing.JTable jtDepedente;
    private javax.swing.JLabel lbHotel;
    private javax.swing.JLabel lbViagem;
    private javax.swing.JList<String> listBusca;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCaQuarto;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel painelDepedente;
    private javax.swing.JPanel painelOcupantes;
    private javax.swing.JPanel painelOrganizaQuarto;
    private javax.swing.JPanel painelQuarto;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JSpinner txtCamaCasal;
    private javax.swing.JSpinner txtCamaSolteiro;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
    
    private void chaveBackground(boolean b){
        painelOrganizaQuarto.setVisible(b);
    }
    
    private void carregaTela(String v) {
        lbHotel.setText(hotel.getNome());
        lbViagem.setText(v);
        jCBDepedente.setSelected(false);
        jCBDepedenteItemStateChanged(null);
    }

    private void carregaTable() {
        modeloDepedente = new DepedenteTableModel();
        jtDepedente.setModel(modeloDepedente);
        int t = jtDepedente.getSize().width;
        jtDepedente.getColumnModel().getColumn(0).setPreferredWidth((int) (t * 0.7));
        jtDepedente.getColumnModel().getColumn(1).setPreferredWidth((int) (t * 0.3));
        
        modeloOcupante = new OcupanteTableModel();
        jTOcupantes.setModel(modeloOcupante);
    }

}
