/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turism.gui;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import turism.controle.CidadeDAO;
import turism.controle.ClienteDAO;
import turism.controle.ContratoDAO;
import turism.controle.EstadoDAO;
import turism.controle.PaisDAO;
import turism.controle.ParcelaDAO;
import turism.controle.ViagemDAO;
import turism.modelo.Cidade;
import turism.modelo.Cliente;
import turism.modelo.Contrato;
import turism.modelo.Estado;
import turism.modelo.Pais;
import turism.modelo.Parcela;
import turism.modelo.Viagem;
import turism.regra.ParcelaTableModel;
import turism.regra.ViagemTableModel;

/**
 *
 * @author matheus
 */
public class TelaParcela extends javax.swing.JFrame {
    
    private static final Locale BRAZIL = new Locale("pt", "BR");
    private static final DecimalFormatSymbols REAL = new DecimalFormatSymbols(BRAZIL);
    public static final DecimalFormat DINHEIRO_REAL = new DecimalFormat("¤ ###,###,##0.00", REAL);
    public static final DecimalFormat ITENS = new DecimalFormat("###,###,##0");

    ArrayList<Pais> paises = new ArrayList<>();
    ArrayList<Estado> estados = new ArrayList<>();
    ArrayList<Cidade> origens = new ArrayList<>();
    ArrayList<Cidade> destinos = new ArrayList<>();

    ArrayList<Viagem> viagens = new ArrayList<>();
    ArrayList<Contrato> contratos = new ArrayList<>();

    ArrayList<Cliente> clientes = new ArrayList<>();
    ArrayList<Parcela> parcelas = new ArrayList<>();

    ViagemTableModel modeloViagem;
    ParcelaTableModel modeloParcela;

    Cliente cliente = new Cliente();
    Viagem viagem = new Viagem();
    Contrato contrato = new Contrato();

    ParcelaDAO pDAO = new ParcelaDAO();

    /**
     * Creates new form TelaParcela
     */
    public TelaParcela() {
        modeloViagem = new ViagemTableModel();
        modeloParcela = new ParcelaTableModel();
        initComponents();
        jInternalBuscaViagem.setVisible(false);
        jInternalBuscaCliente.setVisible(false);
        this.tamanhoTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalBuscaCliente = new javax.swing.JInternalFrame();
        painelCliente = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBusca = new javax.swing.JList<>();
        jInternalBuscaViagem = new javax.swing.JInternalFrame();
        btnBuscarViagem1 = new javax.swing.JButton();
        dataIdaBusca = new com.toedter.calendar.JDateChooser();
        dataVoltaBusca = new com.toedter.calendar.JDateChooser();
        PainelOrigem1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbCidadeOrigem = new javax.swing.JComboBox<>();
        jbEstadoOrigem = new javax.swing.JComboBox<>();
        jbPaisOrigem = new javax.swing.JComboBox<>();
        PainelDestino1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jbCidadeDestino = new javax.swing.JComboBox<>();
        jbEstadoDestino = new javax.swing.JComboBox<>();
        jbPaisDestino = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtViagem = new javax.swing.JTable();
        painelParcela = new javax.swing.JPanel();
        txtViagem = new javax.swing.JTextField();
        btnBuscarViagem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        painelParcelasTable = new javax.swing.JPanel();
        painelBotoes = new javax.swing.JPanel();
        btnPagarParcela = new javax.swing.JButton();
        dataPagamento = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTParcela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorFaltante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parcela");
        setPreferredSize(new java.awt.Dimension(960, 410));

        jInternalBuscaCliente.setVisible(true);
        jInternalBuscaCliente.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalBuscaClienteInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Busca Cliente:"));

        txtBusca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaCaretUpdate(evt);
            }
        });
        txtBusca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        listBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBuscaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listBusca);

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtBusca)))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jInternalBuscaClienteLayout = new javax.swing.GroupLayout(jInternalBuscaCliente.getContentPane());
        jInternalBuscaCliente.getContentPane().setLayout(jInternalBuscaClienteLayout);
        jInternalBuscaClienteLayout.setHorizontalGroup(
            jInternalBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jInternalBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalBuscaClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jInternalBuscaClienteLayout.setVerticalGroup(
            jInternalBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
            .addGroup(jInternalBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalBuscaClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jInternalBuscaViagem.setClosable(true);
        jInternalBuscaViagem.setTitle("Busca Viagem");
        jInternalBuscaViagem.setVisible(true);
        jInternalBuscaViagem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInternalBuscaViagemFocusGained(evt);
            }
        });
        jInternalBuscaViagem.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalBuscaViagemInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnBuscarViagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/search_64.png"))); // NOI18N
        btnBuscarViagem1.setText("Buscar Viagem");
        btnBuscarViagem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarViagem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarViagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViagem1ActionPerformed(evt);
            }
        });

        dataIdaBusca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataIdaBuscaPropertyChange(evt);
            }
        });

        dataVoltaBusca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataVoltaBuscaPropertyChange(evt);
            }
        });

        PainelOrigem1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Origem:"));

        jLabel13.setText("Cidade:");

        jLabel16.setText("UF:");

        jLabel15.setText("País:");

        jbEstadoOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbEstadoOrigemItemStateChanged(evt);
            }
        });

        jbPaisOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbPaisOrigemItemStateChanged(evt);
            }
        });
        jbPaisOrigem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jbPaisOrigemPropertyChange(evt);
            }
        });
        jbPaisOrigem.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jbPaisOrigemVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout PainelOrigem1Layout = new javax.swing.GroupLayout(PainelOrigem1);
        PainelOrigem1.setLayout(PainelOrigem1Layout);
        PainelOrigem1Layout.setHorizontalGroup(
            PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPaisOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelOrigem1Layout.createSequentialGroup()
                        .addComponent(jbEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelOrigem1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(74, 74, 74)
                        .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addComponent(jbCidadeOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PainelOrigem1Layout.setVerticalGroup(
            PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PainelDestino1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Destino:"));

        jLabel14.setText("País:");

        jLabel23.setText("UF:");

        jLabel24.setText("Cidade:");

        jbCidadeDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbCidadeDestinoFocusLost(evt);
            }
        });

        jbEstadoDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbEstadoDestinoItemStateChanged(evt);
            }
        });

        jbPaisDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbPaisDestinoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PainelDestino1Layout = new javax.swing.GroupLayout(PainelDestino1);
        PainelDestino1.setLayout(PainelDestino1Layout);
        PainelDestino1Layout.setHorizontalGroup(
            PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDestino1Layout.createSequentialGroup()
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDestino1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(133, 133, 133))
                    .addGroup(PainelDestino1Layout.createSequentialGroup()
                        .addComponent(jbPaisDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jbEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jbCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelDestino1Layout.setVerticalGroup(
            PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDestino1Layout.createSequentialGroup()
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel25.setText("Data de Ida:");

        jLabel26.setText("Data de Volta:");

        jtViagem.setModel(modeloViagem);
        jtViagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtViagemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtViagem);

        javax.swing.GroupLayout jInternalBuscaViagemLayout = new javax.swing.GroupLayout(jInternalBuscaViagem.getContentPane());
        jInternalBuscaViagem.getContentPane().setLayout(jInternalBuscaViagemLayout);
        jInternalBuscaViagemLayout.setHorizontalGroup(
            jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                        .addComponent(PainelOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(dataIdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)))
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarViagem1)
                                .addGap(63, 63, 63))
                            .addComponent(dataVoltaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jInternalBuscaViagemLayout.setVerticalGroup(
            jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarViagem1))
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel25))
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataIdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataVoltaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        dataIdaBusca.getJCalendar().setMinSelectableDate(new Date());

        painelParcela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelParcela.setPreferredSize(new java.awt.Dimension(300, 500));

        txtViagem.setEditable(false);

        btnBuscarViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViagemActionPerformed(evt);
            }
        });

        jLabel2.setText("Viagem:");

        txtCliente.setEditable(false);

        jLabel1.setText("Cliente:");

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        painelParcelasTable.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Parcelas"));

        painelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPagarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/finance_64.png"))); // NOI18N
        btnPagarParcela.setText("Pagar");
        btnPagarParcela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagarParcela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarParcelaActionPerformed(evt);
            }
        });

        dataPagamento.setDate(new Date());

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnPagarParcela)
                .addGap(24, 24, 24))
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagarParcela))
        );

        jTParcela.setModel(modeloParcela);
        jTParcela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTParcela);

        javax.swing.GroupLayout painelParcelasTableLayout = new javax.swing.GroupLayout(painelParcelasTable);
        painelParcelasTable.setLayout(painelParcelasTableLayout);
        painelParcelasTableLayout.setHorizontalGroup(
            painelParcelasTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelParcelasTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelParcelasTableLayout.setVerticalGroup(
            painelParcelasTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParcelasTableLayout.createSequentialGroup()
                .addGroup(painelParcelasTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setText("Valor Recebido:");

        jLabel4.setText("Valor Total:");

        txtValorRecebido.setEditable(false);

        txtValorTotal.setEditable(false);

        jLabel5.setText("Valor Faltante:");

        txtValorFaltante.setEditable(false);

        javax.swing.GroupLayout painelParcelaLayout = new javax.swing.GroupLayout(painelParcela);
        painelParcela.setLayout(painelParcelaLayout);
        painelParcelaLayout.setHorizontalGroup(
            painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParcelaLayout.createSequentialGroup()
                .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(painelParcelasTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtValorFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscarViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelParcelaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelParcelaLayout.setVerticalGroup(
            painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParcelaLayout.createSequentialGroup()
                .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelParcelaLayout.createSequentialGroup()
                                .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(6, 6, 6)
                                .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(txtCliente)))
                            .addComponent(btnBuscarViagem)))
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBuscarCliente)))
                .addGap(12, 12, 12)
                .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(painelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelParcelaLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtValorTotal))
                            .addGroup(painelParcelaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelParcelaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(painelParcelasTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jInternalBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(jInternalBuscaViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelParcela, 775, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(jInternalBuscaViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelParcela, 457, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarViagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViagem1ActionPerformed
        // TODO add your handling code here:
        int indo = jbCidadeOrigem.getSelectedIndex();
        int indd = jbCidadeDestino.getSelectedIndex();
        System.err.println(indo + " " + indd);
        if (indo > -1 && indd > -1) {
            CidadeDAO ciDAO = new CidadeDAO();
            Cidade origem = ciDAO.buscaCidade(origens.get(indo).getIdcidade());
            Cidade destino = ciDAO.buscaCidade(destinos.get(indd).getIdcidade());
            this.buscaViagem(origem.getIdcidade(), destino.getIdcidade(), dataIdaBusca.getDate(), dataVoltaBusca.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma cidade de origem e uma cidade de destino");
        }
    }//GEN-LAST:event_btnBuscarViagem1ActionPerformed

    private void dataIdaBuscaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataIdaBuscaPropertyChange
        // TODO add your handling code here:
        dataVoltaBusca.getJCalendar().setMinSelectableDate(dataIdaBusca.getDate());
        dataVoltaBusca.requestFocus();
    }//GEN-LAST:event_dataIdaBuscaPropertyChange

    private void dataVoltaBuscaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataVoltaBuscaPropertyChange
        // TODO add your handling code here:
        btnBuscarViagem.requestFocus();
    }//GEN-LAST:event_dataVoltaBuscaPropertyChange

    private void jbEstadoOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbEstadoOrigemItemStateChanged
        // TODO add your handling code here:
        int indice = jbEstadoOrigem.getSelectedIndex();
        if (indice >= 0) {
            origens.clear();
            EstadoDAO eDAO = new EstadoDAO();
            Estado e = eDAO.buscaEstado(estados.get(indice).getIdestado());
            origens = e.getCidadeList();
            jbCidadeOrigem.removeAllItems();
            if (!origens.isEmpty()) {
                origens.forEach((next) -> {
                    jbCidadeOrigem.addItem(next.getNome());
                });
                jbCidadeOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbEstadoOrigemItemStateChanged

    private void jbPaisOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbPaisOrigemItemStateChanged
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemItemStateChanged

    private void jbPaisOrigemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jbPaisOrigemPropertyChange
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemPropertyChange

    private void jbPaisOrigemVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jbPaisOrigemVetoableChange
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemVetoableChange

    private void jbCidadeDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbCidadeDestinoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCidadeDestinoFocusLost

    private void jbEstadoDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbEstadoDestinoItemStateChanged
        // TODO add your handling code here:
        int indice = jbEstadoDestino.getSelectedIndex();
        if (indice >= 0) {
            destinos.clear();
            EstadoDAO eDAO = new EstadoDAO();
            Estado e = eDAO.buscaEstado(estados.get(indice).getIdestado());
            destinos = e.getCidadeList();
            jbCidadeDestino.removeAllItems();
            if (!destinos.isEmpty()) {
                destinos.forEach((next) -> {
                    jbCidadeDestino.addItem(next.getNome());
                });
                jbCidadeDestino.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbEstadoDestinoItemStateChanged

    private void jbPaisDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbPaisDestinoItemStateChanged
        // TODO add your handling code here:
        int indice = jbPaisDestino.getSelectedIndex();
        if (indice >= 0) {
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(indice + 1);
            jbEstadoDestino.removeAllItems();
            if (!p.getEstadoList().isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoDestino.addItem(next.getUf());
                });
                jbEstadoDestino.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisDestinoItemStateChanged

    private void jtViagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtViagemMouseClicked
        // TODO add your handling code here:
        int indice = jtViagem.getSelectedRow();
        if (indice > -1) {
            ViagemDAO vDAO = new ViagemDAO();
            viagem = vDAO.buscaViagem(viagens.get(indice).getIdviagem());
            //contrato.setIdviagem(viagem);
            jInternalBuscaViagem.setVisible(false);
            this.chaveBackground(true);
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            txtViagem.setText(viagem.getIdorigem().getNome() + " á " + viagem.getIddestino().getNome() + " Data: " + df.format(viagem.getDataida()));
            this.carregaContrato();
        }
    }//GEN-LAST:event_jtViagemMouseClicked

    private void jInternalBuscaViagemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalBuscaViagemFocusGained

    }//GEN-LAST:event_jInternalBuscaViagemFocusGained

    private void jInternalBuscaViagemInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalBuscaViagemInternalFrameClosed
        // TODO add your handling code here:
        chaveBackground(true);
        jInternalBuscaViagem.setVisible(false);
    }//GEN-LAST:event_jInternalBuscaViagemInternalFrameClosed

    private void btnBuscarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViagemActionPerformed
        // TODO add your handling code here:
        this.chaveBackground(false);
        jInternalBuscaViagem.setVisible(true);
        ViagemDAO vDAO = new ViagemDAO();
        viagens = vDAO.carregaViagem();
        modeloViagem.limpar();
        modeloViagem.addListaViagem(viagens);
        this.carregaPais();
    }//GEN-LAST:event_btnBuscarViagemActionPerformed

    private void txtBuscaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaCaretUpdate
        // TODO add your handling code here:
        ClienteDAO ciDAO = new ClienteDAO();
        clientes.clear();
        clientes = ciDAO.buscaClienteParcelado(viagem.getIdviagem(), txtBusca.getText());
        listBusca.removeAll();
        DefaultListModel modelol = new DefaultListModel();
        clientes.forEach((next) -> {
            modelol.addElement(next.getNome());
        });
        listBusca.setModel(modelol);
        listBusca.repaint();
    }//GEN-LAST:event_txtBuscaCaretUpdate

    private void txtBuscaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaInputMethodTextChanged

    private void listBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBuscaMouseClicked
        // TODO add your handling code here:
        int indice = listBusca.getSelectedIndex();
        if (indice >= 0) {
            cliente = clientes.get(indice);
            this.carregaParcela();
            jInternalBuscaCliente.setVisible(false);
            this.chaveBackground(true);
            txtCliente.setText(cliente.getNome());
            this.valor();
        }
    }//GEN-LAST:event_listBuscaMouseClicked

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        if (viagem.getIdviagem() != null) {
            this.chaveBackground(false);
            jInternalBuscaCliente.setVisible(true);
            ClienteDAO ciDAO = new ClienteDAO();
            clientes.clear();
            clientes = ciDAO.buscaClienteParcelado(viagem.getIdviagem(), "");
            listBusca.removeAll();
            DefaultListModel modelol = new DefaultListModel();
            clientes.forEach((next) -> {
                modelol.addElement(next.getNome());
            });
            listBusca.setModel(modelol);
            listBusca.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma viagem antes!");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void jInternalBuscaClienteInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalBuscaClienteInternalFrameClosed
        // TODO add your handling code here:
        jInternalBuscaCliente.setVisible(false);
        this.chaveBackground(true);
    }//GEN-LAST:event_jInternalBuscaClienteInternalFrameClosed

    private void btnPagarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarParcelaActionPerformed
        // TODO add your handling code here:
        int indice = jTParcela.getSelectedRow();
        if(indice > -1){
            Parcela p = parcelas.get(indice);
            p.setPaga(true);
            p.setDatapagamento(dataPagamento.getDate());
            pDAO.atualizar(p);
            this.carregaParcela();
            this.valor();
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma parcela á ser paga!");
        }
    }//GEN-LAST:event_btnPagarParcelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParcela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaParcela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelDestino1;
    private javax.swing.JPanel PainelOrigem1;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarViagem;
    private javax.swing.JButton btnBuscarViagem1;
    private javax.swing.JButton btnPagarParcela;
    private com.toedter.calendar.JDateChooser dataIdaBusca;
    private com.toedter.calendar.JDateChooser dataPagamento;
    private com.toedter.calendar.JDateChooser dataVoltaBusca;
    private javax.swing.JInternalFrame jInternalBuscaCliente;
    private javax.swing.JInternalFrame jInternalBuscaViagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTParcela;
    private javax.swing.JComboBox<String> jbCidadeDestino;
    private javax.swing.JComboBox<String> jbCidadeOrigem;
    private javax.swing.JComboBox<String> jbEstadoDestino;
    private javax.swing.JComboBox<String> jbEstadoOrigem;
    private javax.swing.JComboBox<String> jbPaisDestino;
    private javax.swing.JComboBox<String> jbPaisOrigem;
    private javax.swing.JTable jtViagem;
    private javax.swing.JList<String> listBusca;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel painelParcela;
    private javax.swing.JPanel painelParcelasTable;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtValorFaltante;
    private javax.swing.JTextField txtValorRecebido;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtViagem;
    // End of variables declaration//GEN-END:variables

    private void chaveBackground(boolean b) {
        painelParcela.setVisible(b);
    }

    private void carregaPais() {
        paises.clear();
        PaisDAO paDAO = new PaisDAO();
        paises = paDAO.buscaPaises("");
        jbPaisOrigem.removeAllItems();
        jbPaisDestino.removeAllItems();
        paises.forEach((next) -> {
            jbPaisOrigem.addItem(next.getNome());
            jbPaisDestino.addItem(next.getNome());
        });
        jbPaisOrigem.setSelectedIndex(-1);
        jbPaisDestino.setSelectedIndex(-1);
        jbEstadoOrigem.removeAllItems();
        jbEstadoOrigem.setSelectedIndex(-1);
        jbCidadeOrigem.removeAllItems();
        jbCidadeOrigem.setSelectedIndex(-1);
    }

    private void buscaViagem(int origem, int destino, Date ida, Date volta) {
        if (origem < 0 || destino < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma cidade de origem e uma cidade de destino");
        } else {
            ViagemDAO vDAO = new ViagemDAO();
            if (ida != null && volta != null) {
                viagens = vDAO.buscaViagem(origem, destino, ida, volta);
            } else if (ida != null) {
                viagens = vDAO.buscaViagem(origem, destino, ida);
            } else {
                viagens = vDAO.buscaViagem(origem, destino);
            }
        }
        modeloViagem.limpar();
        modeloViagem.addListaViagem(viagens);
    }

    private void carregaContrato() {
        contratos.clear();
        ContratoDAO cDAO = new ContratoDAO();
        contratos = cDAO.buscaContratoViagemParcelado(viagem.getIdviagem());
    }

    private void carregaParcela() {
        parcelas.clear();
        contratos.stream().filter((contrat) -> (contrat.getIdcliente().equals(cliente))).forEachOrdered((contrat) -> {
            contrato = contrat;
        });
        parcelas = pDAO.buscaParcelaViagemContrato(viagem.getIdviagem(), contrato.getIdcontrato());
        modeloParcela.limpar();
        modeloParcela.addListaPArcela(parcelas);
    }
    
    private void valor(){
        double total = 0, parcial = 0;
        if(!parcelas.isEmpty()){
            for (Parcela parc : parcelas) {
                total += parc.getValor();
                if(parc.getPaga()){
                    parcial += parc.getValor();
                }
            }
        }
        txtValorRecebido.setText(DINHEIRO_REAL.format(parcial));
        txtValorTotal.setText(DINHEIRO_REAL.format(total));
        txtValorFaltante.setText(DINHEIRO_REAL.format(total-parcial));
    }
    
    private void tamanhoTabela() {
        int t = jTParcela.getSize().width;
        jTParcela.getColumnModel().getColumn(0).setPreferredWidth((int) (t * 0.2));
        jTParcela.getColumnModel().getColumn(1).setPreferredWidth((int) (t * 0.3));
        jTParcela.getColumnModel().getColumn(2).setPreferredWidth((int) (t * 0.3));
        jTParcela.getColumnModel().getColumn(3).setPreferredWidth((int) (t * 0.2));
    }
    
}
