/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turism.gui;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import turism.controle.AssentoDAO;
import turism.controle.CidadeDAO;
import turism.controle.ContratoDAO;
import turism.controle.EstadoDAO;
import turism.controle.HoteisContratadosDAO;
import turism.controle.PaisDAO;
import turism.controle.ParcelaDAO;
import turism.controle.VeiculosContratadosDAO;
import turism.controle.ViagemDAO;
import turism.modelo.AssentoPK;
import turism.modelo.Cidade;
import turism.modelo.Contrato;
import turism.modelo.Estado;
import turism.modelo.Hoteiscontratados;
import turism.modelo.HoteiscontratadosPK;
import turism.modelo.Hotel;
import turism.modelo.Pais;
import turism.modelo.Parcela;
import turism.modelo.Veiculo;
import turism.modelo.Veiculoscontratados;
import turism.modelo.VeiculoscontratadosPK;
import turism.modelo.Viagem;
import turism.regra.ContratoTableModel;
import turism.regra.ViagemTableModel;

/**
 *
 * @author matheus
 */
public class TelaViagemGerenciamento extends javax.swing.JFrame {

    private static final Locale BRAZIL = new Locale("pt", "BR");
    private static final DecimalFormatSymbols REAL = new DecimalFormatSymbols(BRAZIL);
    public static final DecimalFormat DINHEIRO_REAL = new DecimalFormat("¤ ###,###,##0.00", REAL);
    public static final DecimalFormat ITENS = new DecimalFormat("###,###,##0");

    Viagem viagem = new Viagem();
    ViagemDAO vDAO = new ViagemDAO();

    ArrayList<Viagem> viagens = new ArrayList<>();
    ArrayList<Contrato> contratos = new ArrayList<>();
    Map<AssentoPK, Boolean> ocupados = new HashMap<>();
    ArrayList<Hoteiscontratados> hoteiscontratados = new ArrayList<>();
    ArrayList<HoteiscontratadosPK> hoteiscontratadospk = new ArrayList<>();
    ArrayList<Veiculoscontratados> veiculoscontratados = new ArrayList<>();
    ArrayList<VeiculoscontratadosPK> veiculoscontratadospk = new ArrayList<>();

    ArrayList<Pais> paises = new ArrayList<>();
    ArrayList<Estado> estados = new ArrayList<>();
    ArrayList<Cidade> origens = new ArrayList<>();
    ArrayList<Cidade> destinos = new ArrayList<>();

    ViagemTableModel modeloViagem;
    ContratoTableModel modeloContrato;

    /**
     * Creates new form TelaViagemGerenciamento
     */
    public TelaViagemGerenciamento() {
        initComponents();
        this.carregaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEscolheHotel = new javax.swing.JButton();
        painelViagem = new javax.swing.JPanel();
        txtViagem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarViagem = new javax.swing.JButton();
        painelValor = new javax.swing.JPanel();
        txtValorRecebido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtValorHotel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorOnibus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValorPessoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValorFaltante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        painelVagas = new javax.swing.JPanel();
        txtVagaTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVagaRestante = new javax.swing.JTextField();
        txtVagaExtra = new javax.swing.JTextField();
        txtVagaOcupadas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        painelContrato = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTContrato = new javax.swing.JTable();
        painelBotoesContrato = new javax.swing.JPanel();
        btnExcluirContrato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnEscolheOnibus = new javax.swing.JButton();
        jInternalBuscaViagem = new javax.swing.JInternalFrame();
        btnBuscarViagem1 = new javax.swing.JButton();
        dataIdaBusca = new com.toedter.calendar.JDateChooser();
        dataVoltaBusca = new com.toedter.calendar.JDateChooser();
        PainelOrigem1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbCidadeOrigem = new javax.swing.JComboBox<>();
        jbEstadoOrigem = new javax.swing.JComboBox<>();
        jbPaisOrigem = new javax.swing.JComboBox<>();
        PainelDestino1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jbCidadeDestino = new javax.swing.JComboBox<>();
        jbEstadoDestino = new javax.swing.JComboBox<>();
        jbPaisDestino = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtViagem = new javax.swing.JTable();
        jInternalEscolha = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jCBEscolha = new javax.swing.JComboBox<>();
        btnEscolha = new javax.swing.JButton();

        btnEscolheHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/hotel_64.png"))); // NOI18N
        btnEscolheHotel.setText("Hotel");
        btnEscolheHotel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEscolheHotel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEscolheHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolheHotelActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Viagem");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        txtViagem.setEditable(false);

        jLabel2.setText("Viagem:");

        btnBuscarViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/search_find.png"))); // NOI18N
        btnBuscarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViagemActionPerformed(evt);
            }
        });

        painelValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtValorRecebido.setEditable(false);

        jLabel1.setText("Valor Recebido:");

        txtValorTotal.setEditable(false);

        jLabel12.setText("Valor Total:");

        txtValorHotel.setEditable(false);

        jLabel11.setText("Valor do Hotel:");

        txtValorOnibus.setEditable(false);

        jLabel10.setText("Valor do Ônibus:");

        txtValorPessoa.setEditable(false);

        jLabel9.setText("Valor por Pessoa:");

        txtValorFaltante.setEditable(false);

        jLabel3.setText("Valor Faltante:");

        javax.swing.GroupLayout painelValorLayout = new javax.swing.GroupLayout(painelValor);
        painelValor.setLayout(painelValorLayout);
        painelValorLayout.setHorizontalGroup(
            painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelValorLayout.createSequentialGroup()
                        .addComponent(txtValorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelValorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(32, 32, 32)
                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtValorFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelValorLayout.setVerticalGroup(
            painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelValorLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(painelValorLayout.createSequentialGroup()
                        .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorRecebido)
                            .addGroup(painelValorLayout.createSequentialGroup()
                                .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtValorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtValorHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        painelVagas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtVagaTotal.setEditable(false);

        jLabel6.setText("Vagas Total:");

        jLabel7.setText("Vagas Restante:");

        jLabel8.setText("Vagas Extras:");

        txtVagaRestante.setEditable(false);

        txtVagaExtra.setEditable(false);

        txtVagaOcupadas.setEditable(false);

        jLabel17.setText("Vagas Ocupadas:");

        javax.swing.GroupLayout painelVagasLayout = new javax.swing.GroupLayout(painelVagas);
        painelVagas.setLayout(painelVagasLayout);
        painelVagasLayout.setHorizontalGroup(
            painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVagasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtVagaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtVagaOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtVagaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVagaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(98, 98, 98))
        );
        painelVagasLayout.setVerticalGroup(
            painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVagasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelVagasLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVagaOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelVagasLayout.createSequentialGroup()
                        .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVagaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVagaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVagaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        painelContrato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTContrato.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTContrato);

        btnExcluirContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/delete_64.png"))); // NOI18N
        btnExcluirContrato.setText("Excluir");
        btnExcluirContrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirContrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContratoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/Update_64.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesContratoLayout = new javax.swing.GroupLayout(painelBotoesContrato);
        painelBotoesContrato.setLayout(painelBotoesContratoLayout);
        painelBotoesContratoLayout.setHorizontalGroup(
            painelBotoesContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesContratoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluirContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesContratoLayout.setVerticalGroup(
            painelBotoesContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesContratoLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirContrato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelContratoLayout = new javax.swing.GroupLayout(painelContrato);
        painelContrato.setLayout(painelContratoLayout);
        painelContratoLayout.setHorizontalGroup(
            painelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContratoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelBotoesContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        painelContratoLayout.setVerticalGroup(
            painelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelContratoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(painelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(painelBotoesContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnEscolheOnibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/bus_64.png"))); // NOI18N
        btnEscolheOnibus.setText("Ônibus");
        btnEscolheOnibus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEscolheOnibus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEscolheOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolheOnibusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelViagemLayout = new javax.swing.GroupLayout(painelViagem);
        painelViagem.setLayout(painelViagemLayout);
        painelViagemLayout.setHorizontalGroup(
            painelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(painelViagemLayout.createSequentialGroup()
                        .addComponent(txtViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelViagemLayout.createSequentialGroup()
                .addComponent(painelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 169, Short.MAX_VALUE))
            .addGroup(painelViagemLayout.createSequentialGroup()
                .addGroup(painelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelVagas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscolheOnibus)
                .addGap(36, 36, 36))
        );
        painelViagemLayout.setVerticalGroup(
            painelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelViagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscolheOnibus)
                .addGap(343, 343, 343))
        );

        jInternalBuscaViagem.setClosable(true);
        jInternalBuscaViagem.setTitle("Busca Viagem");
        jInternalBuscaViagem.setMinimumSize(new java.awt.Dimension(954, 405));
        jInternalBuscaViagem.setVisible(false);
        jInternalBuscaViagem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInternalBuscaViagemFocusGained(evt);
            }
        });
        jInternalBuscaViagem.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalBuscaViagemInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnBuscarViagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turism/imagens/padrao/search_64.png"))); // NOI18N
        btnBuscarViagem1.setText("Buscar Viagem");
        btnBuscarViagem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarViagem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarViagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViagem1ActionPerformed(evt);
            }
        });

        dataIdaBusca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataIdaBuscaPropertyChange(evt);
            }
        });

        dataVoltaBusca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataVoltaBuscaPropertyChange(evt);
            }
        });

        PainelOrigem1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Origem:"));

        jLabel13.setText("Cidade:");

        jLabel16.setText("UF:");

        jLabel15.setText("País:");

        jbEstadoOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbEstadoOrigemItemStateChanged(evt);
            }
        });

        jbPaisOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbPaisOrigemItemStateChanged(evt);
            }
        });
        jbPaisOrigem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jbPaisOrigemPropertyChange(evt);
            }
        });
        jbPaisOrigem.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jbPaisOrigemVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout PainelOrigem1Layout = new javax.swing.GroupLayout(PainelOrigem1);
        PainelOrigem1.setLayout(PainelOrigem1Layout);
        PainelOrigem1Layout.setHorizontalGroup(
            PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPaisOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelOrigem1Layout.createSequentialGroup()
                        .addComponent(jbEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelOrigem1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(74, 74, 74)
                        .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addComponent(jbCidadeOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PainelOrigem1Layout.setVerticalGroup(
            PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrigem1Layout.createSequentialGroup()
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelOrigem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PainelDestino1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Destino:"));

        jLabel14.setText("País:");

        jLabel23.setText("UF:");

        jLabel24.setText("Cidade:");

        jbCidadeDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbCidadeDestinoFocusLost(evt);
            }
        });

        jbEstadoDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbEstadoDestinoItemStateChanged(evt);
            }
        });

        jbPaisDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbPaisDestinoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PainelDestino1Layout = new javax.swing.GroupLayout(PainelDestino1);
        PainelDestino1.setLayout(PainelDestino1Layout);
        PainelDestino1Layout.setHorizontalGroup(
            PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDestino1Layout.createSequentialGroup()
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDestino1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(133, 133, 133))
                    .addGroup(PainelDestino1Layout.createSequentialGroup()
                        .addComponent(jbPaisDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jbEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jbCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelDestino1Layout.setVerticalGroup(
            PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDestino1Layout.createSequentialGroup()
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelDestino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel25.setText("Data de Ida:");

        jLabel26.setText("Data de Volta:");

        jtViagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtViagem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtViagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtViagemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtViagem);

        javax.swing.GroupLayout jInternalBuscaViagemLayout = new javax.swing.GroupLayout(jInternalBuscaViagem.getContentPane());
        jInternalBuscaViagem.getContentPane().setLayout(jInternalBuscaViagemLayout);
        jInternalBuscaViagemLayout.setHorizontalGroup(
            jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                        .addComponent(PainelOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(dataIdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)))
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarViagem1)
                                .addGap(63, 63, 63))
                            .addComponent(dataVoltaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jInternalBuscaViagemLayout.setVerticalGroup(
            jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelOrigem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarViagem1))
                    .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel25))
                            .addGroup(jInternalBuscaViagemLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalBuscaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataIdaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataVoltaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        dataIdaBusca.getJCalendar().setMinSelectableDate(new Date());

        jInternalEscolha.setClosable(true);
        jInternalEscolha.setVisible(false);
        jInternalEscolha.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalEscolhaInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel4.setText("Selecione um:");

        btnEscolha.setText("Ok");
        btnEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalEscolhaLayout = new javax.swing.GroupLayout(jInternalEscolha.getContentPane());
        jInternalEscolha.getContentPane().setLayout(jInternalEscolhaLayout);
        jInternalEscolhaLayout.setHorizontalGroup(
            jInternalEscolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalEscolhaLayout.createSequentialGroup()
                .addGroup(jInternalEscolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalEscolhaLayout.createSequentialGroup()
                        .addGroup(jInternalEscolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalEscolhaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jInternalEscolhaLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnEscolha)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCBEscolha, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalEscolhaLayout.setVerticalGroup(
            jInternalEscolhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalEscolhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscolha)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalBuscaViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(500, 500, 500)
                    .addComponent(jInternalEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(500, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalBuscaViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(363, 363, 363)
                    .addComponent(jInternalEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViagemActionPerformed
        // TODO add your handling code here:
        this.chaveBackground(false);
        jInternalBuscaViagem.setVisible(true);
//        Dimension dmnsn = new Dimension(954, 405);
//        jInternalBuscaViagem.setSize(954, 405);
//        jInternalBuscaViagem.setMinimumSize(dmnsn);
//        jInternalBuscaViagem.setLocation(0, 0);
        vDAO = new ViagemDAO();
        viagens = vDAO.carregaViagem();
        modeloViagem.limpar();
        modeloViagem.addListaViagem(viagens);
        this.carregaPais();
    }//GEN-LAST:event_btnBuscarViagemActionPerformed

    private void btnBuscarViagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViagem1ActionPerformed
        // TODO add your handling code here:
        int indo = jbCidadeOrigem.getSelectedIndex();
        int indd = jbCidadeDestino.getSelectedIndex();
        System.err.println(indo + " " + indd);
        if (indo > -1 && indd > -1) {
            CidadeDAO ciDAO = new CidadeDAO();
            Cidade origem = ciDAO.buscaCidade(origens.get(indo).getIdcidade());
            Cidade destino = ciDAO.buscaCidade(destinos.get(indd).getIdcidade());
            this.buscaViagem(origem.getIdcidade(), destino.getIdcidade(), dataIdaBusca.getDate(), dataVoltaBusca.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma cidade de origem e uma cidade de destino");
        }
    }//GEN-LAST:event_btnBuscarViagem1ActionPerformed

    private void dataIdaBuscaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataIdaBuscaPropertyChange
        // TODO add your handling code here:
        dataVoltaBusca.getJCalendar().setMinSelectableDate(dataIdaBusca.getDate());
        dataVoltaBusca.requestFocus();
    }//GEN-LAST:event_dataIdaBuscaPropertyChange

    private void dataVoltaBuscaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataVoltaBuscaPropertyChange
        // TODO add your handling code here:
        btnBuscarViagem.requestFocus();
    }//GEN-LAST:event_dataVoltaBuscaPropertyChange

    private void jbEstadoOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbEstadoOrigemItemStateChanged
        // TODO add your handling code here:
        int indice = jbEstadoOrigem.getSelectedIndex();
        if (indice >= 0) {
            origens.clear();
            EstadoDAO eDAO = new EstadoDAO();
            Estado e = eDAO.buscaEstado(estados.get(indice).getIdestado());
            origens = e.getCidadeList();
            jbCidadeOrigem.removeAllItems();
            if (!origens.isEmpty()) {
                origens.forEach((next) -> {
                    jbCidadeOrigem.addItem(next.getNome());
                });
                jbCidadeOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbEstadoOrigemItemStateChanged

    private void jbPaisOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbPaisOrigemItemStateChanged
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemItemStateChanged

    private void jbPaisOrigemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jbPaisOrigemPropertyChange
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemPropertyChange

    private void jbPaisOrigemVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jbPaisOrigemVetoableChange
        // TODO add your handling code here:
        int indice = jbPaisOrigem.getSelectedIndex();
        if (indice >= 0) {
            estados.clear();
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(paises.get(indice).getIdpais());
            estados = p.getEstadoList();
            jbEstadoOrigem.removeAllItems();
            if (!estados.isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoOrigem.addItem(next.getUf());
                });
                jbEstadoOrigem.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisOrigemVetoableChange

    private void jbCidadeDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbCidadeDestinoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCidadeDestinoFocusLost

    private void jbEstadoDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbEstadoDestinoItemStateChanged
        // TODO add your handling code here:
        int indice = jbEstadoDestino.getSelectedIndex();
        if (indice >= 0) {
            destinos.clear();
            EstadoDAO eDAO = new EstadoDAO();
            Estado e = eDAO.buscaEstado(estados.get(indice).getIdestado());
            destinos = e.getCidadeList();
            jbCidadeDestino.removeAllItems();
            if (!destinos.isEmpty()) {
                destinos.forEach((next) -> {
                    jbCidadeDestino.addItem(next.getNome());
                });
                jbCidadeDestino.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbEstadoDestinoItemStateChanged

    private void jbPaisDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbPaisDestinoItemStateChanged
        // TODO add your handling code here:
        int indice = jbPaisDestino.getSelectedIndex();
        if (indice >= 0) {
            PaisDAO paDAO = new PaisDAO();
            Pais p = paDAO.buscaPais(indice + 1);
            jbEstadoDestino.removeAllItems();
            if (!p.getEstadoList().isEmpty()) {
                p.getEstadoList().forEach((next) -> {
                    jbEstadoDestino.addItem(next.getUf());
                });
                jbEstadoDestino.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_jbPaisDestinoItemStateChanged

    private void jtViagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtViagemMouseClicked
        // TODO add your handling code here:
        int indice = jtViagem.getSelectedRow();
        if (indice > -1) {
            viagem = vDAO.buscaViagem(viagens.get(indice).getIdviagem());
            //contrato.setIdviagem(viagem);
            jInternalBuscaViagem.setVisible(false);
            this.chaveBackground(true);
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            txtViagem.setText(viagem.getIdorigem().getNome() + " á " + viagem.getIddestino().getNome() + " Data: " + df.format(viagem.getDataida()));
            HoteisContratadosDAO hcDAO = new HoteisContratadosDAO();
            VeiculosContratadosDAO vcDAO = new VeiculosContratadosDAO();
            hoteiscontratados = hcDAO.buscaHoteisContratadosViagem(viagem.getIdviagem());
            veiculoscontratados = vcDAO.buscaVeiculosContratadosViagem(viagem.getIdviagem());
            this.carregaContratos();
            this.carregaAssento(viagem.getIdviagem());
            this.vagasTotal();
            this.valorTotal();
        }
    }//GEN-LAST:event_jtViagemMouseClicked

    private void jInternalBuscaViagemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalBuscaViagemFocusGained

    }//GEN-LAST:event_jInternalBuscaViagemFocusGained

    private void jInternalBuscaViagemInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalBuscaViagemInternalFrameClosed
        // TODO add your handling code here:
        chaveBackground(true);
        jInternalBuscaViagem.setVisible(false);
    }//GEN-LAST:event_jInternalBuscaViagemInternalFrameClosed

    private void btnExcluirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContratoActionPerformed
        // TODO add your handling code here:
        int indice = jTContrato.getSelectedRow();
        if(indice > -1){
            int op = JOptionPane.showConfirmDialog(this, "Deseja excluir o Contrato? ");
            if(op == JOptionPane.YES_OPTION){
                ContratoDAO cDAO = new ContratoDAO();
                Contrato c = contratos.get(indice);
                cDAO.apagar(c);
                JOptionPane.showMessageDialog(this, "Contrato excluído!");
                this.carregaAssento(viagem.getIdviagem());
                this.carregaContratos();
                this.vagasTotal();
                this.valorTotal();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um Contrato na Tabela!");
        }
    }//GEN-LAST:event_btnExcluirContratoActionPerformed

    private void btnEscolheOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolheOnibusActionPerformed
        // TODO add your handling code here:
        jInternalEscolha.setVisible(true);
        chaveBackground(false);
        carregaVeiculo();
    }//GEN-LAST:event_btnEscolheOnibusActionPerformed

    private void btnEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolhaActionPerformed
        // TODO add your handling code here:
        int indice = jCBEscolha.getSelectedIndex();
        if(indice > -1) {
            if (veiculoscontratados.get(indice).getVeiculo().getNome().equalsIgnoreCase(jCBEscolha.getSelectedItem().toString())) {
                Veiculo v = veiculoscontratados.get(indice).getVeiculo();
                JFrame janela = new TelaVeiculoAssento(v, txtViagem.getText());
                janela.setVisible(true);
                janela.setLocationRelativeTo(null);
                janela.setResizable(false);
                janela.toFront();
            }else if(hoteiscontratados.get(indice).getHotel().getNome().equalsIgnoreCase(jCBEscolha.getSelectedItem().toString())){
                Hoteiscontratados hc = hoteiscontratados.get(indice);
                JFrame janela = new TelaHotelViagem(hc, txtViagem.getText());
                janela.setVisible(true);
                janela.setLocationRelativeTo(null);
                janela.setResizable(false);
                janela.toFront();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Escolha um Veiculo ou Hotel para Gerenciar!");
        }
    }//GEN-LAST:event_btnEscolhaActionPerformed

    private void jInternalEscolhaInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalEscolhaInternalFrameClosed
        // TODO add your handling code here:
        this.chaveBackground(true);
    }//GEN-LAST:event_jInternalEscolhaInternalFrameClosed

    private void btnEscolheHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolheHotelActionPerformed
        // TODO add your handling code here:
        jInternalEscolha.setVisible(true);
        chaveBackground(false);
        carregaHotel();
    }//GEN-LAST:event_btnEscolheHotelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int indice = jTContrato.getSelectedRow();
        Contrato c = contratos.get(indice);
        JFrame janela = new TelaContratoGerenciamento(c);
        janela.setVisible(true);
        janela.setLocationRelativeTo(null);
        janela.setResizable(false);
        janela.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(viagem.getIdviagem() != null){
            this.vagasTotal();
            this.valorTotal();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaViagemGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaViagemGerenciamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelDestino1;
    private javax.swing.JPanel PainelOrigem1;
    private javax.swing.JButton btnBuscarViagem;
    private javax.swing.JButton btnBuscarViagem1;
    private javax.swing.JButton btnEscolha;
    private javax.swing.JButton btnEscolheHotel;
    private javax.swing.JButton btnEscolheOnibus;
    private javax.swing.JButton btnExcluirContrato;
    private com.toedter.calendar.JDateChooser dataIdaBusca;
    private com.toedter.calendar.JDateChooser dataVoltaBusca;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBEscolha;
    private javax.swing.JInternalFrame jInternalBuscaViagem;
    private javax.swing.JInternalFrame jInternalEscolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTContrato;
    private javax.swing.JComboBox<String> jbCidadeDestino;
    private javax.swing.JComboBox<String> jbCidadeOrigem;
    private javax.swing.JComboBox<String> jbEstadoDestino;
    private javax.swing.JComboBox<String> jbEstadoOrigem;
    private javax.swing.JComboBox<String> jbPaisDestino;
    private javax.swing.JComboBox<String> jbPaisOrigem;
    private javax.swing.JTable jtViagem;
    private javax.swing.JPanel painelBotoesContrato;
    private javax.swing.JPanel painelContrato;
    private javax.swing.JPanel painelVagas;
    private javax.swing.JPanel painelValor;
    private javax.swing.JPanel painelViagem;
    private javax.swing.JTextField txtVagaExtra;
    private javax.swing.JTextField txtVagaOcupadas;
    private javax.swing.JTextField txtVagaRestante;
    private javax.swing.JTextField txtVagaTotal;
    private javax.swing.JTextField txtValorFaltante;
    private javax.swing.JTextField txtValorHotel;
    private javax.swing.JTextField txtValorOnibus;
    private javax.swing.JTextField txtValorPessoa;
    private javax.swing.JTextField txtValorRecebido;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtViagem;
    // End of variables declaration//GEN-END:variables

    private void chaveBackground(boolean b) {
        painelViagem.setVisible(b);
    }

    private void carregaPais() {
        paises.clear();
        PaisDAO paDAO = new PaisDAO();
        paises = paDAO.buscaPaises("");
        jbPaisOrigem.removeAllItems();
        jbPaisDestino.removeAllItems();
        paises.forEach((next) -> {
            jbPaisOrigem.addItem(next.getNome());
            jbPaisDestino.addItem(next.getNome());
        });
        jbPaisOrigem.setSelectedIndex(-1);
        jbPaisDestino.setSelectedIndex(-1);
        jbEstadoOrigem.removeAllItems();
        jbEstadoOrigem.setSelectedIndex(-1);
        jbCidadeOrigem.removeAllItems();
        jbCidadeOrigem.setSelectedIndex(-1);
    }

    private void carregaVeiculo() {
        jCBEscolha.removeAllItems();
        veiculoscontratados.forEach((next) -> {
            jCBEscolha.addItem(next.getVeiculo().getNome());
        });
        jCBEscolha.setSelectedIndex(-1);
    }

    private void carregaHotel() {
        jCBEscolha.removeAllItems();
        hoteiscontratados.forEach((next) -> {
            jCBEscolha.addItem(next.getHotel().getNome());
        });
        jCBEscolha.setSelectedIndex(-1);
    }

    private void buscaViagem(int origem, int destino, Date ida, Date volta) {
        if (origem < 0 || destino < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma cidade de origem e uma cidade de destino");
        } else {
            if (ida != null && volta != null) {
                viagens = vDAO.buscaViagem(origem, destino, ida, volta);
            } else if (ida != null) {
                viagens = vDAO.buscaViagem(origem, destino, ida);
            } else {
                viagens = vDAO.buscaViagem(origem, destino);
            }
        }
        modeloViagem.limpar();
        modeloViagem.addListaViagem(viagens);
    }

    private void carregaTable() {
        modeloViagem = new ViagemTableModel();
        jtViagem.setModel(modeloViagem);

        modeloContrato = new ContratoTableModel();
        jTContrato.setModel(modeloContrato);
        int t = jTContrato.getSize().width;
        jTContrato.getColumnModel().getColumn(0).setPreferredWidth((int) (t * 0.5));
        jTContrato.getColumnModel().getColumn(1).setPreferredWidth((int) (t * 0.1));
        jTContrato.getColumnModel().getColumn(2).setPreferredWidth((int) (t * 0.2));
        jTContrato.getColumnModel().getColumn(3).setPreferredWidth((int) (t * 0.2));
    }

    private int vagasTotal() {
        int total = 0, ocupadas = 0;
        if (!veiculoscontratados.isEmpty() || veiculoscontratados != null) {
            total = veiculoscontratados.stream().map((next) -> next.getVeiculo().getLotacao()).reduce(total, Integer::sum);
        }
        
        if (!ocupados.isEmpty()) {

            ocupadas = ocupados.size();
        }
        
        total += viagem.getVagasextras();
        txtVagaTotal.setText(ITENS.format(total));
        txtVagaExtra.setText(ITENS.format(viagem.getVagasextras()));
        txtVagaOcupadas.setText(ITENS.format(ocupadas));
        txtVagaRestante.setText(ITENS.format((total - ocupadas)));
        return total;
    }

    private void valorTotal() {
        double total, onibus = 0, hotel = 0, recebido;
        if (!veiculoscontratados.isEmpty()) {
            for (Veiculoscontratados next : veiculoscontratados) {
                if (next.getValor() > onibus) {
                    onibus = next.getValor();
                }
            }
            txtValorOnibus.setText(String.valueOf(DINHEIRO_REAL.format(onibus * this.vagasTotal())));
        }
        if (!hoteiscontratados.isEmpty()) {
            for (Hoteiscontratados hoteu : hoteiscontratados) {
                if (hoteu.getValor() > hotel) {
                    hotel = hoteu.getValor();
                }
            }
            txtValorHotel.setText(String.valueOf(DINHEIRO_REAL.format(hotel * this.vagasTotal())));
        }
        if (veiculoscontratados.isEmpty()) {
            txtValorOnibus.setText(String.valueOf(DINHEIRO_REAL.format(onibus * this.vagasTotal())));
        }
        if (hoteiscontratados.isEmpty()) {
            txtValorHotel.setText(String.valueOf(DINHEIRO_REAL.format(hotel * this.vagasTotal())));
        }

        total = onibus + hotel;
        recebido = this.valorPago();

        txtValorPessoa.setText(String.valueOf(DINHEIRO_REAL.format(total)));
        txtValorTotal.setText(String.valueOf(DINHEIRO_REAL.format(total * this.vagasTotal())));
        txtValorFaltante.setText(DINHEIRO_REAL.format((total * this.vagasTotal()) - recebido));
        txtValorRecebido.setText(DINHEIRO_REAL.format(recebido));
    }

    private void carregaContratos() {
        ContratoDAO cDAO = new ContratoDAO();
        contratos = cDAO.buscaContratoViagem(viagem.getIdviagem());
        modeloContrato.limpar();
        modeloContrato.addListaContratos(contratos);
    }

    private void carregaAssento(int idvi) {
        AssentoDAO aDAO = new AssentoDAO();
        ocupados.clear();
        aDAO.buscaAssento(idvi).forEach((assent) -> {
            ocupados.put(assent, true);
        });
    }

    private double valorPago() {
        double total = 0, tpessoa;

        for (Contrato c : contratos) {
            tpessoa = 0;
            ParcelaDAO pDAO = new ParcelaDAO();

            ArrayList<Parcela> parcelas = new ArrayList<>();

            if (c.getIdforma().getIdformapagamento() == 1) {
                parcelas = pDAO.buscaParcelaViagemContrato(c.getIdviagem().getIdviagem(), c.getIdcontrato());
            } else if (c.getIdforma().getIdformapagamento() == 2) {
                tpessoa = this.valorTotal(c);
            }

            if (!parcelas.isEmpty()) {
                for (Parcela parcela : parcelas) {
                    if (parcela.getPaga()) {
                        tpessoa += parcela.getValor();
                    }
                }
            }
            total +=tpessoa;
        }
        return total;
    }

    private double valorTotal(Contrato c) {
        double onibus = 0, hotel = 0;

        AssentoDAO aDAO = new AssentoDAO();
        ArrayList<AssentoPK> apk = aDAO.buscaAssentoContrato(c.getIdcontrato());
        if (!veiculoscontratados.isEmpty()) {
            for (Veiculoscontratados nextc : veiculoscontratados) {
                for (AssentoPK apks : apk) {
                    if (nextc.getVeiculo().getIdveiculo() == apks.getIdveiculo()) {
                        if (nextc.getValor() > onibus) {
                            onibus = nextc.getValor();
                        }
                    }
                }

            }
        }
        
        if (!hoteiscontratados.isEmpty()) {
            for (Hoteiscontratados hoteu : hoteiscontratados) {
                if (hoteu.getValor() > hotel) {
                    hotel = hoteu.getValor();
                }
            }
        }

        return (onibus + hotel)*c.getQuantidade();
    }
}
